// To run the generator, run `swift generator.swift`.
import Foundation

/// Whether an integer type is signed or unsigned.
enum SignednessPrefix: String, CustomStringConvertible {
  case signed = "s"
  case unsigned = "u"

  var description: String {
    return self.rawValue
  }

  var humanFriendlyDescription: String {
    switch self {
    case .signed:
      return "A signed"
    case .unsigned:
      return "An unsigned"
    }
  }
}

/// The size of an integer type.
enum Size {
  /// The type is capable of representing the size of the largest object in memory on the target platform.
  case size

  /// The type has exactly `bits` bits.
  case fixedWidth(bits: Int)

  var humanFriendlyDescription: String {
    switch self {
    case .size:
      return "size-representing"
    case .fixedWidth(let bits):
      return "\(bits)-bit"
    }
  }
}

/// Information for emitting a standard library integer type.
struct IntegerTypeDefinition: CustomStringConvertible {
  let name: String
  let builtinType: String
  let signedness: SignednessPrefix
  let size: Size

  /// Constructs an integer type definition from its parts.
  init(name: String, builtinType: String, _ signedness: SignednessPrefix, _ size: Size) {
    self.name = name
    self.builtinType = builtinType
    self.signedness = signedness
    self.size = size
  }

  /// The code introducing the `abs()` method for signed types.
  var absMethod: String {
    switch signedness {
    case .signed:
      return
        """

          /// Returns the absolute value of `self`.
          ///
          /// - Precondition: `self` must not be the \(name)'s minimum value.
          public fun abs() -> Self {
            if self < Self.zero() { Self.zero() - self } else { Self(value: self.value) }
          }
        """
    case .unsigned:
      return ""
    }
  }

  /// The source code representation of this type, without conversions.
  var description: String {
    """
    // Generated by ../../../generator.swift.

    /// \(signedness.humanFriendlyDescription) \(size.humanFriendlyDescription) integer value.
    @_symbol(\"\(name)\")
    public struct \(name) is Deinitializable {

      /// The raw value of this instance.
      internal var value: Builtin.\(builtinType)

      /// Creates an instance with its raw value.
      internal memberwise init

      /// Creates an instance equal to `false`.
      public init() {
        &self.value = Builtin.zeroinitializer_\(builtinType)()
      }
    \(absMethod)

    }

    public given \(name) is ExpressibleByIntegerLiteral { /* built-in */ }

    public given \(name) is Movable {}

    public given \(name) is Equatable {

      /// Returns `true` if `self` is equal to `other`.
      public fun infix== (other: Self) -> Bool {
        .new(value: Builtin.icmp_eq_\(builtinType)(self.value, other.value))
      }

      /// Returns `true` if `self` is not equal to `other`.
      public fun infix!= (other: Self) -> Bool {
        .new(value: Builtin.icmp_ne_\(builtinType)(self.value, other.value))
      }

    }

    public given \(name) is Comparable {

      /// Returns `true` if `self` is less than `other`.
      public fun infix< (other: Self) -> Bool {
        .new(value: Builtin.icmp_\(signedness)lt_\(builtinType)(self.value, other.value))
      }

      /// Returns `true` if `self` is less than or equal to `other`.
      public fun infix<= (other: Self) -> Bool {
        .new(value: Builtin.icmp_\(signedness)le_\(builtinType)(self.value, other.value))
      }

      /// Returns `true` if `self` is greater than `other`.
      public fun infix> (other: Self) -> Bool {
        .new(value: Builtin.icmp_\(signedness)gt_\(builtinType)(self.value, other.value))
      }

      /// Returns `true` if `self` is greater than or equal to `other`.
      public fun infix>= (_ other: Self) -> Bool {
        .new(value: Builtin.icmp_\(signedness)ge_\(builtinType)(self.value, other.value))
      }

    }

    public given \(name) is AdditiveArithmetic {

      /// Returns `self` added to `other`.
      fun infix+ (other: Self) -> Self {
        let (result, overflow) = Builtin.\(signedness)add_with_overflow_\(builtinType)(self.value, other.value)
        if Bool(value: overflow) {
          fatal_error()
        } else {
          return .new(value: result)
        }
      }

      /// Returns `other` subtracted from `self`.
      fun infix- (other: Self) -> Self {
        let (result, overflow) = Builtin.\(signedness)sub_with_overflow_\(builtinType)(self.value, other.value)
        if Bool(value: overflow) {
          fatal_error()
        } else {
          return .new(value: result)
        }
      }

      /// Returns `0`.
      static fun zero() -> Self {
        .new()
      }

    }

    public given \(name) is Numeric {

      /// Returns `self` multiplied by `other`.
      fun infix* (other: Self) -> Self {
        let (result, overflow) = Builtin.\(signedness)mul_with_overflow_\(builtinType)(self.value, other.value)
        if Bool(value: overflow) {
          fatal_error()
        } else {
          return .new(value: result)
        }
      }

    }
    """
  }
}

var integerTypes: [IntegerTypeDefinition] = []

// Add fixed-width integer types:
for bits in [8, 16, 32, 64] {
  integerTypes.append(
    .init(name: "Int\(bits)", builtinType: "i\(bits)", .signed, .fixedWidth(bits: bits)))
  integerTypes.append(
    .init(name: "UInt\(bits)", builtinType: "i\(bits)", .unsigned, .fixedWidth(bits: bits)))
}

// Add target-dependent integer types:
integerTypes.append(.init(name: "Int", builtinType: "word", .signed, .size))
integerTypes.append(.init(name: "UInt", builtinType: "word", .unsigned, .size))

for t in integerTypes {
  try String(describing: t).write(
    to: URL(fileURLWithPath: "\(#filePath)/../Sources/Core/Numbers/\(t.name).hylo"),
    atomically: true, encoding: .utf8)
}
