extension TypeStore {

  /// Returns the type of a continuation generated by the projection, which is:
  /// `{[](let ptr) let -> Void, ptr}`
  internal mutating func projectionContinuationType() -> AnyTypeIdentity {
    let addressType = demand(MachineType.ptr).erased
    let t = demand(Arrow(
      inputs: [
        Parameter(access: .`let`, type: addressType)
      ],
      output: .void
    ))
    return tuple(of: [t.erased, addressType])
  }

  /// Returns the type of a continuation that is able to call a caller plateau, projecting a value
  /// of type `p`.
  ///
  /// The type is `{[](inout p, let ptr, let {[](let ptr) let -> Void, ptr}) let -> Void, ptr}`.
  internal mutating func plateauContinuationType(
    projectedType p: AnyTypeIdentity
  ) -> AnyTypeIdentity {
    let addressType = demand(MachineType.ptr).erased

    let t = demand(Arrow(
      inputs: [
        Parameter(access: .`inout`, type: p),
        Parameter(access: .`let`, type: addressType),
        Parameter(access: .`let`, type: projectionContinuationType()),
      ],
      output: .void
    ))
    return tuple(of: [t.erased, addressType])
  }
}

extension IREmitter {

  /// Returns the IR function representing the ramp of projection `f`.
  /// 
  /// - Requires: `f` is a projection.
  /// - Requires: `f` doesn't have type parameters.
  ///
  /// Signature:
  ///
  ///     fun Projection.ramp(_ c: let PlateauContinuation, <parameters>) -> {}
  ///
  /// Generated function parameters:
  ///   - `c`: the continuation used to resume the flow in the plateau,
  ///     containing the function to call and the caller frame pointer.
  ///   - `<parameters>`: the original parameters of the projection
  internal mutating func demandProjectionRamp(for f: IRFunction) -> IRFunction.ID {
    // Do we have a ramp for `f` already?
    let n = IRFunction.Name.ramp(f.name)
    if let i = program[module].ir.functions.index(forKey: n) {
      return i
    }

    precondition(f.typeParameters.isEmpty,
      "projection ramp cannot be generated for a generic function")

    guard case .remote(_, let r) = f.output else {
      preconditionFailure("projection ramp can only be generated for projections")
    }
    // Note: we ignore the access effect of the projected type.

    var inputs = f.termParameters
    let c = program.types.plateauContinuationType(projectedType: r)
    inputs.insert(IRParameter(type: c, access: .`let`), at: 0)

    return program[module].ir.addFunction(IRFunction(
      name: n, output: .indirect, typeParameters: [], termParameters: inputs))
  }

  /// Returns the IR function representing the slide of projection `f`.
  ///
  /// - Requires: `f` is a projection.
  /// - Requires: `f` doesn't have type parameters.
  ///
  /// Signature:
  ///
  ///     fun Projection.slide(_ frame: let Builtin.ptr) -> {}
  ///
  /// Generated function parameters:
  ///   - `frame`: the projection frame pointer.
  internal mutating func demandProjectionSlide(for f: IRFunction) -> IRFunction.ID {
    // Do we have a slide for `f` already?
    let n = IRFunction.Name.slide(f.name)
    if let i = program[module].ir.functions.index(forKey: n) {
      return i
    }

    precondition(f.typeParameters.isEmpty,
      "projection slide cannot be generated for a generic function")

    let inputs = [IRParameter(type: .void, access: .`let`)]
    return program[module].ir.addFunction(IRFunction(
      name: n, output: .indirect, typeParameters: [], termParameters: inputs))
  }

  /// Returns the IR function representing a plateau region in caller `f` corresponding to the
  /// projected value type `t`.
  /// 
  /// `index` is used to distinguish multiple plateaus in the same caller.
  ///
  /// - Requires: `f` doesn't have type parameters.
  ///
  /// Signature:
  ///
  ///       fun Caller.plateauN(
  ///         _ p: inout <yield-type>, _ frame: let Builtin.ptr, _ c: let ProjectionContinuation
  ///       ) -> {}
  ///
  /// Generated function parameters:
  ///   - `p`: the projected value.
  ///   - `frame`: the address of the caller frame.
  ///   - `c`: the continuation used to resume to the projection's slide,
  ///     containing the function to call and the projection frame pointer.
  internal mutating func demandPlateau(
    for f: IRFunction, index: Int, projectedType t: AnyTypeIdentity,
  ) -> IRFunction.ID {
    // Do we have a plateau for `f` already?
    let n = IRFunction.Name.plateau(f.name, index)
    if let i = program[module].ir.functions.index(forKey: n) {
      return i
    }

    precondition(f.typeParameters.isEmpty, "plateau cannot be generated for a generic function")

    let inputs = [
      IRParameter(type: t, access: .`inout`),
      IRParameter(type: program.types.demand(MachineType.ptr).erased, access: .`let`),
      IRParameter(type: program.types.projectionContinuationType(), access: .`let`)
    ]

    return program[module].ir.addFunction(IRFunction(
      name: n, output: .indirect, typeParameters: [], termParameters: inputs))
  }

}
