ARG HYLO_LLVM_BUILD_TYPE=MinSizeRel

# Temporary pin on the LLVM 23 pre-release image, which ships a single build type; switch back to
# a tagged image once https://github.com/hylo-lang/hylo-dev-toolchain/pull/15 is released.
FROM ghcr.io/hylo-lang/hylo-dev-toolchain:pr-15-1805f10
