import ArgumentParser
import Foundation

/// The top-level command of `hc-generate-stdlib`.
@main struct CommandLine: ParsableCommand {

  @Option(
    help: ArgumentHelp(
      "The output directory to generate Hylo declarations into. (Default: StandardLibrary/Sources/Core/Generated)"
    ),
    transform: URL.init(fileURLWithPath:))
  private var output: URL = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .appending(path: "StandardLibrary/Sources/Core/Generated")

  /// Executes the CLI command, generating output files within `output`
  public func run() throws {
    let integers = try generateIntegerTypes()
    try integers.write(
      to: output.appending(path: "Integers.hylo"),
      atomically: true, encoding: .utf8)


    try Self.disclaimer.write(
      to: output.appending(path: "README.md"),
      atomically: true, encoding: .utf8)
  }

  static let disclaimer: String =
    """
    Generated by hc-generate-stdlib.

    On Linux and Windows this generation is part of the build process thanks to
    GenerateHyloStdLibPlugin, but on MacOS you need to run the generator manually
    after changing it:

    ```bash
    swift run hc-generate-stdlib
    ```

    """

}
