import FrontEnd
import Interpreter

extension String {
  /// Interpret `self` as `SourceFile`.
  var sourceFile: SourceFile {
    // TODO: Needed `asSourceFile` from OFE. However, `SourceFile` needs some
    // amount of work for the same.
    SourceFile(contents: self)
  }
}

/// Runs program in `s` on `Interpreter`.
func runOnInterpreter(_ s: SourceFile) async throws {
  var p = Program()
  let m = p.demandModule("Main")
  p[m].addDependency(Module.standardLibraryName)
  _ = p[m].addSource(s)

  await p.assignScopes(m)
  p.assignTypes(m, loggingInferenceWhere: { _, _ in false })
  if p[m].containsError {
    printDiagnostics(p[m])
    throw ProgramError.typeCheckingFailed
  }

  p.lower(m)
  p.applyTransformationPasses(m)
  if p[m].containsError {
    printDiagnostics(p[m])
    throw ProgramError.loweringFailed
  }

  var logger = TreePrinter(program: p)

  var executor = Interpreter(p)
  while executor.isRunning {
    print(executor.currentInstruction.show(using: &logger))
    try executor.step()
  }
}

/// Print diagnostics in `m`.
private func printDiagnostics(_ m: Module) {
  for d in m.diagnostics {
    var r = ""
    d.render(into: &r, style: .unstyled)
    print(r, terminator: "")
  }
}

/// Error generated by `Program` while processing.
private enum ProgramError: Error {
  /// Error during type checking.
  case typeCheckingFailed

  /// Error during IR lowering.
  case loweringFailed
}
