import Foundation
import FrontEnd
import Interpreter

/// Execute `p` on interpreter and prints all the instruction executed.
private func execute(_ p: Program) throws {
  var logger = TreePrinter(program: p)

  var executor = Interpreter(p)
  while executor.isRunning {
    print(executor.currentInstruction.show(using: &logger))
    try executor.step()
  }
}

extension URL {

  /// Runs program at `u` on `Interpreter`.
  func interpret() async throws {
    var p = try loadProgramWithStandardLibrary()
    let m = p.identity(module: "Main")!

    try await assignScopes(in: m, of: &p)
    try assignTypes(in: m, of: &p)
    try lowerToIR(m, in: &p)
    try applyTransformationPasses(to: m, of: &p)

    try execute(p)
  }

  /// Returns `Program` at `self` containing `Main` module alongwith standard library.
  private func loadProgramWithStandardLibrary() throws -> Program {
    let s = try SourceFile(contentsOf: self)
    var p = Program()
    let m = p.demandModule("Main")
    p[m].addDependency(Module.standardLibraryName)
    _ = p[m].addSource(s)
    return p
  }

  /// Assign lexical scopes to declrations in `m` of `p`.
  private func assignScopes(in m: Module.ID, of p: inout Program) async throws {
    await p.assignScopes(m)
    if p[m].containsError {
      throw CompilerError(diagnostics: Array(p[m].diagnostics))
    }
  }

  /// Assign types in `m` of `p`.
  private func assignTypes(in m: Module.ID, of p: inout Program) throws {
    p.assignTypes(m, loggingInferenceWhere: { _, _ in false })
    if p[m].containsError {
      throw CompilerError(diagnostics: Array(p[m].diagnostics))
    }
  }

  /// Lowers module `m` of `p` to IR.
  private func lowerToIR(_ m: Module.ID, in p: inout Program) throws {
    p.lower(m)
    if p[m].containsError {
      throw CompilerError(diagnostics: Array(p[m].diagnostics))
    }
  }

  /// Applies transformation passes to `m` of `p`.
  private func applyTransformationPasses(to m: Module.ID, of p: inout Program) throws {
    p.applyTransformationPasses(m)
    if p[m].containsError {
      throw CompilerError(diagnostics: Array(p[m].diagnostics))
    }
  }
}

/// Error generated by compiler while processing a program.
private struct CompilerError: LocalizedError {

  /// Diagnostics generated while compiling program.
  public let diagnostics: [FrontEnd.Diagnostic]

  /// A human readable string listing all `diagnostics`.
  var errorDescription: String? {
    var r = ""
    for d in diagnostics {
      d.render(into: &r, style: .unstyled)
    }
    return r
  }

}
