import Foundation
import FrontEnd
import Interpreter

/// Execute `p` on interpreter and prints all the instruction executed.
private func execute(_ p: Program) throws {
  var logger = TreePrinter(program: p)

  var executor = Interpreter(p)
  while executor.isRunning {
    print(executor.currentInstruction.show(using: &logger))
    try executor.step()
  }
}

extension URL {

  /// Runs program at `self` on `Interpreter`.
  func interpret() async throws {
    var p = try loadProgramWithStandardLibrary()
    let m = p.identity(module: "Main")!

    try await p.requireNoError(in: m) { await $0.assignScopes(m) }
    try p.requireNoError(in: m) { $0.assignTypes(m, loggingInferenceWhere: { _, _ in false }) }
    try p.requireNoError(in: m) { $0.lower(m) }
    try p.requireNoError(in: m) { $0.applyTransformationPasses(m) }

    try execute(p)
  }

  /// Returns `Program` at `self` containing `Main` module alongwith standard library.
  private func loadProgramWithStandardLibrary() throws -> Program {
    let s = try SourceFile(contentsOf: self)
    var p = Program()
    let m = p.demandModule("Main")
    p[m].addDependency(Module.standardLibraryName)
    _ = p[m].addSource(s)
    return p
  }

}

/// Error generated by compiler while processing a program.
private struct CompilerError: LocalizedError {

  /// Diagnostics generated while compiling program.
  public let diagnostics: [FrontEnd.Diagnostic]

  /// A human readable string listing all `diagnostics`.
  var errorDescription: String? {
    var r = ""
    for d in diagnostics {
      d.render(into: &r, style: .unstyled)
    }
    return r
  }

}

extension Program {

  /// Throws iff `m` contains error.
  private func requireNoError(in m: Module.ID) throws {
    if self[m].containsError {
      throw CompilerError(diagnostics: Array(self[m].diagnostics))
    }
  }

  /// Invokes `action` with `self` and throws iff there is any error in `m`.
  fileprivate mutating func requireNoError(
    in m: Module.ID,
    after action: (inout Program) async -> Void
  ) async throws {
    await action(&self)
    try requireNoError(in: m)
  }

  /// Invokes `action` with `self` and throws iff there is any error in `m`.
  fileprivate mutating func requireNoError(
    in m: Module.ID,
    after action: (inout Program) -> Void
  ) throws {
    action(&self)
    try requireNoError(in: m)
  }

}
